# Generated by Django 3.0 on 2020-04-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200422_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desce',
            field=models.CharField(default='', max_length=500),
        ),
    ]
